[INSEE v3] update documentation
etalab/doc.entreprise.api.gouv.fr pull request #5
Opened 2018-07-18 13:42 UTC by Haelle

Mise à jour de la documentation pour intégrer la reconstruction des APIs `v2/etablissements` et `v2/entreprises` à partir de la nouvelle API de l'INSEE (api.insee.fr)

P.S: la section de doc pour établissements ne contient pas l'avertissement pour la TVA car elle n'est que dans entreprises

![screenshot](https://screenshotscdn.firefoxusercontent.com/images/f4f66be7-1be4-47fe-b739-90e183f44803.png)

2018-07-18 14:24 UTC, hugolepetit commented
Numéro TVA ajouter en gros, cette donnée est théorique. Le calcul seul ne suffit pas a tout garantir

2018-09-10 12:41 UTC, Haelle commented
maj : 
![screenshot](https://screenshots.firefox.com/7yQvGwCCUtLn1qff/10.7.130.126)

2018-10-28 10:51 UTC, Haelle commented
MAJ avec le nouveau champ `with_etat_administratif`

![screenshot](https://screenshotscdn.firefoxusercontent.com/images/afbdd2ea-9c3a-4261-90b3-abbcc86c1af7.png)

2018-10-29 12:49 UTC, giglemad commented on source/includes/etablissements/_etablissements.md.erb
> +A compter du XX/XX/2018 cette API est re-construite à partir des données de <a href="https://api.insse.fr">la nouvelle API de l'INSEE</a>
Est ce que ce XX/XX/XX appelle une valeur en particulier, n'est pas connue ?

2018-10-29 12:51 UTC, hugolepetit requested changes
* Réponse au point sur la date en XX/XX/XX nécessaire
* Reformulation pour englober non pas uniquement la limite de 38 chars qui saute mais d'autres types de modification. Si pas assez clair on peut ajouter : `(par exemple, le formattage des champs en 38 caractères)` 

OK otherwise, modifs a faire, pas besoin de review additionnelle pour merge

2018-10-30 06:40 UTC, Haelle commented on source/includes/etablissements/_etablissements.md.erb
> +A compter du XX/XX/2018 cette API est re-construite à partir des données de <a href="https://api.insse.fr">la nouvelle API de l'INSEE</a>
Quand on aura décidé quand on remplace la v2 INSEE par la v3 je mettrai une date ;)

2018-10-30 06:45 UTC, Haelle commented
mise à jour de la phrase en question en : 
```
La valeur des champs l1-7 peut donc différer des anciennes valeurs, par exemple la taille des champs peut dépasser les 38 caractères maximum imposés par la norme RNVP.
```

2018-10-30 09:57 UTC, hugolepetit commented on source/includes/etablissements/_etablissements.md.erb
> +A compter du XX/XX/2018 cette API est re-construite à partir des données de <a href="https://api.insse.fr">la nouvelle API de l'INSEE</a>
On peut rappeler la date au plus tard fournie par l'INSEE et dire que la transition se fera un peu avant pour prendre de la marge si ça te va

2018-10-30 09:59 UTC, giglemad commented
Ok pour ça
Cordialement

Hugo pour API Entreprise
https://entreprise.api.gouv.fr
https://entreprise.api.gouv.fr/documentation
https://dashboard.entreprise.api.gouv.fr



Le mar. 30 oct. 2018 à 07:45, Alexis Leclerc <notifications@github.com> a
écrit :

> mise à jour de la phrase en question en :
>
> La valeur des champs l1-7 peut donc différer des anciennes valeurs, par exemple la taille des champs peut dépasser les 38 caractères maximum imposés par la norme RNVP.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/etalab/doc.entreprise.api.gouv.fr/pull/5#issuecomment-434189735>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACG9RjoXvchlwxrelNJeWm93b1a8XL1Aks5up_WjgaJpZM4VUn5s>
> .
>

2018-10-30 13:34 UTC, Haelle commented
j'ai ajouté des phrases du style : " Cet API sera coupé en juin 2019, reportez-vous sur l'API v2/entreprises "

2018-10-30 14:01 UTC, giglemad commented
Ok. Il faut néanmoins ajouter ces dates / milestones dans la rubrique migrations / evolutions en temps que calendrier

2018-10-30 14:01 UTC, hugolepetit approved these changes

2018-11-05 08:44 UTC, Haelle commented
Dernière version à la place on parle du nouveau champ `with_insee_v3`. La date sera mise à jour une fois la PR API Entreprive liée mergée.

![screenshot](https://screenshotscdn.firefoxusercontent.com/images/02d5bfd7-6658-4113-af22-e538da042e7c.png)

2018-11-15 16:08 UTC, merged